#!/usr/bin/env python

import pinotify.module_system       as mod
import pinotify.plugins.display     as dsp
import pinotify.plugins.email_check as eml
import pinotify.plugins.clock       as clk


config = read_config('/etc/pinotify/pinotify.ini');

# Register modules
modules = {
    'Email_check': eml.email_check(),
    'Display':     dsp.display(),
    'Clock':       clk.clock()
}

mod.set_modules(modules)
mod.pass_configuration(config)
mod.start_workers()


